# SPDX-FileCopyrightText: 2025 The SayWare development team
#
# SPDX-License-Identifier: CC0-1.0

[graph]
targets = ["x86_64-pc-windows-msvc"]
all-features = true

[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "GPL-3.0-or-later",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
  "Zlib",
]
exceptions = [
  { allow = [
    "CDLA-Permissive-2.0",
  ], crate = "webpki-roots" },
  { allow = [
    "OpenSSL",
  ], crate = "aws-lc-sys" },
]

[bans]
multiple-versions-include-dev = true
deny = [
  { crate = "openssl", use-instead = "rustls" },
  { crate = "openssl-sys", use-instead = "rustls" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
