# SPDX-FileCopyrightText: 2025 The SayWare development team
#
# SPDX-License-Identifier: CC0-1.0

# This is an example of a the final malware configuration
# The MaaS website will modify it whenever we build new malware

[server]
hostname = "localhost"
port = 4321
url_prefix = "prefix"

[malware]
fallback_sentence = "Hello Localhost!"
