# SPDX-FileCopyrightText: 2025 The SayWare development team
#
# SPDX-License-Identifier: CC0-1.0

[forge.secrets]
registryUrl = "REGISTRY_URL"
registryUsername = "REGISTRY_USERNAME"
registryPassword = "REGISTRY_PASSWORD"

[forge.variables]
buildingBranch = "BUILDING_BRANCH"
configurationPath = "CONFIGURATION_PATH"

[server]
workflow = "server.yaml"

[server.containerfilePath]
name = "containerfile_path"
value = "Containerfile"

[server.containerName]
name = "container_name"
value = "sayware-server"

[server.containerVersion]
name = "container_version"
value = "0.1.0"

[malware]
configurationPath = "malware.toml"
workflow = "malware.yaml"

[configurations.serverSide]
server = "configurations/server-side/server.toml"
malware = "configurations/server-side/malware.toml"

[configurations.clientSide.server]
schema = "configurations/client-side/server.schema.json"
ui = "configurations/client-side/server-ui.schema.json"

[configurations.clientSide.malware]
schema = "configurations/client-side/malware.schema.json"
ui = "configurations/client-side/malware-ui.schema.json"

[configurations.outputs.instance]
schema = "configurations/outputs/instance.schema.json"
ui = "configurations/outputs/instance-ui.schema.json"

[configurations.outputs.victims]
schema = "configurations/outputs/victims.schema.json"
ui = "configurations/outputs/victims-ui.schema.json"
