# SPDX-FileCopyrightText: 2025 The SayWare development team
#
# SPDX-License-Identifier: CC0-1.0

[forge]
buildingBranchVariableName = "BUILDING_BRANCH"
configurationPathVariableName = "CONFIGURATION_PATH"

[server]
containerfilePath = "Containerfile"

[malware]
configurationPath = "malware.toml"

[configurations]

[configurations.serverSide]
serverPath = "configurations/server-side/server.toml"
malwarePath = "configurations/server-side/malware.toml"

[configurations.clientSide]
serverPath = "configurations/client-side/server.schema.json"
serverUiPath = "configurations/client-side/server-ui.schema.json"
malwarePath = "configurations/client-side/malware.schema.json"
malwareUiPath = "configurations/client-side/malware-ui.schema.json"
