# SPDX-FileCopyrightText: 2025 The SayWare development team
#
# SPDX-License-Identifier: CC0-1.0

[forge]

[forge.secrets]
registryUrlName = "REGISTRY_URL"
registryUsernameName = "REGISTRY_USERNAME"
registryPasswordName = "REGISTRY_PASSWORD"

[forge.variables]
buildingBranchName = "BUILDING_BRANCH"
configurationPathName = "CONFIGURATION_PATH"

[server]
containerfilePath = "Containerfile"
containerName = "sayware-server"
containerVersion = "0.1.0"
workflowName = "server.yaml"

[malware]
configurationPath = "malware.toml"
workflowName = "malware.yaml"

[configurations]

[configurations.serverSide]
serverPath = "configurations/server-side/server.toml"
malwarePath = "configurations/server-side/malware.toml"

[configurations.clientSide]
serverPath = "configurations/client-side/server.schema.json"
serverUiPath = "configurations/client-side/server-ui.schema.json"
malwarePath = "configurations/client-side/malware.schema.json"
malwareUiPath = "configurations/client-side/malware-ui.schema.json"

[configurations.outputs]
instancePath = "configurations/outputs/instance.schema.json"
instanceUiPath = "configurations/outputs/instance-ui.schema.json"
victimsPath = "configurations/outputs/victims.schema.json"
victimsUiPath = "configurations/outputs/victims-ui.schema.json"
