# SPDX-FileCopyrightText: 2025 The SayWare development team
#
# SPDX-License-Identifier: CC0-1.0

[toolchain]
channel = "nightly"
components = ["rust-src"]
targets = ["x86_64-unknown-linux-musl", "x86_64-pc-windows-msvc"]
