# SPDX-FileCopyrightText: 2025 The SayWare development team
#
# SPDX-License-Identifier: CC0-1.0

[server]

[server.hostname]
function = "@serverHostname()"

[server.port]
from = "port"

[server.urlPrefix]
from = "urlPrefix"
