# SPDX-FileCopyrightText: 2025 The SayWare development team
#
# SPDX-License-Identifier: CC0-1.0

[port]
function = "@randomPort(1024, 65535)"
type = "plaintext"

[urlPrefix]
function = "@randomPathPrefix(5, 15)"
type = "plaintext"
