# SPDX-FileCopyrightText: 2025 The SayWare development team
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "sayware"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
windows-core = { version = "0.61.2" }
windows = { version = "0.61.1", features = ["Win32_Networking_WinHttp"] }
cfonts = { version = "1.2.0" }
