# SPDX-FileCopyrightText: 2025 The SayWare development team
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "sayware"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[[bin]]
name = "sayware"
path = "./src/main.rs"

[dependencies]
windows = { version = "0.62.2", features = [
  "Win32_NetworkManagement_NetManagement",
  "Wdk_System_SystemServices",
  "Win32_System_SystemInformation",
  "Win32_Security_Authentication_Identity",
  "Win32_System_WindowsProgramming",
  "Win32_System_Console",
  "Win32_NetworkManagement_IpHelper",
  "Win32_NetworkManagement_Ndis",
  "Win32_Networking_WinSock",
] }
cfonts = { version = "1.3.0" }
reqwest = { version = "0.12.24", default-features = false, features = [
  "json",
  "rustls-tls",
] }
tokio = { version = "1.48.0" }
sayware-types = { path = "../types" }

[build-dependencies]
quote2 = { version = "0.9.0" }
anyhow = { version = "1.0.100" }
toml = { version = "0.9.8" }
serde = { version = "1.0.228", features = ["derive"] }
rand = { version = "0.9.2" }
