# SPDX-FileCopyrightText: 2025 The SayWare development team
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "sayware"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
windows = { version = "0.61.1", features = [
  "Win32_NetworkManagement_NetManagement",
  "Wdk_System_SystemServices",
  "Win32_System_SystemInformation",
  "Win32_Security_Authentication_Identity",
  "Win32_System_WindowsProgramming",
  "Win32_System_Console",
] }
cfonts = { version = "1.2.0" }
reqwest = { version = "0.12.21", features = ["json"] }
tokio = { version = "1.46.0" }
sayware-types = { path = "../types" }

[build-dependencies]
quote2 = { version = "0.9.0" }
anyhow = { version = "1.0.98" }
toml = { version = "0.8.23" }
serde = { version = "1.0.219", features = ["derive"] }
rand = { version = "0.9.1" }
