---
# SPDX-FileCopyrightText: 2025 The SayWare development team
#
# SPDX-License-Identifier: CC0-1.0
name: Check formatting of the project
on: [push, pull_request]
permissions:
  contents: read
jobs:
  yamlfix:
    name: Check formatting with yamlfix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'
          enable-cache: true
      - name: Check YAML formatting
        run: uvx yamlfix -v --check .
  mdformat:
    name: Check formatting with mdformat
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: '3.13'
          enable-cache: true
      - name: Check Markdown formatting
        run: uvx mdformat --check .
  rustfmt:
    name: Check formatting with rustfmt
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install rustfmt
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Check Rust formatting
        run: cargo fmt -v --all -- --check
  taplo:
    name: Check formatting with taplo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install taplo
        uses: uncenter/setup-taplo@v1
      - name: Check TOML formatting
        run: taplo format --check --verbose
